name: madmom
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.11
  - cython>=3.0
  - numpy>=1.26
  - scipy>=1.11
  - pip
  - pip:
      - mido>=1.3
      - pyfftw
      - pyaudio
      - pytest>=7.0
      - black
      - pre-commit
